name: Generate Snake Animation

on:
  schedule: # Executa automaticamente a cada 12 horas
    - cron: "0 */12 * * *"
  workflow_dispatch: # Permite executar manualmente

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Faz checkout do repositório
      - uses: actions/checkout@v3

      # Gera a animação da cobrinha
      - uses: Platane/snk@v3
        with:
          github_user_name: Rudhery # Substitua por seu usuário
          gif_out_path: dist/github-contribution-grid-snake.gif # Caminho do GIF
          svg_out_path: dist/github-contribution-grid-snake.svg # Caminho do SVG (opcional)

      # Envia os arquivos gerados para uma branch chamada "output"
      - uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
